### PR TITLE
Fix issue #704: Remove warnings during test execution

### LINKED ISSUE #704: Remove warnings during test execution
There are warnings while the tests are executing. We should check why these pop up and fix them

### PR DESCRIPTION
**Pull request by edgarmueller**
Fixes #704: Remove warnings during tests

* Add keys where necessary
* Add default values as undefined is not legal
* Replace deleteFunction with update action in tree renderer
* Replace categorization render methods with component

### CODE REVIEW

File: src/json-forms.tsx [hunk 1]
```diff
@@ -146,9 +146,10 @@ export class JsonFormsElement extends HTMLElement {
     const uischema = this.uiSchema;
 
     this.store = initJsonFormsStore(this.dataObject, schema, uischema);
+    const storeId = new Date().toISOString();
 
     render(
-      <Provider store={this.store}>
+      <Provider store={this.store} key={`${storeId}-store`}>
```
Comment (eneufeld) [inline src/json-forms.tsx]: Is this kind of a UUID?

File: src/reducers/common.ts [hunk 2]
```diff
@@ -38,7 +39,8 @@ export const commonStateReducer = (
         };
       } else {
         const currData = get(state.data, action.path);
-        const newState = set(state.data, action.path, action.updater(currData));
+        const data = action.updater(currData);
```
Comment (eneufeld) [inline src/reducers/common.ts]: shouldn't the variables be named:
`currData` -> `oldData`
`data` -> `newData`
?

File: src/renderers/additional/categorization-renderer.tsx [hunk 3]
```diff
@@ -1,12 +1,89 @@
...
+export interface SingleCategoryProps {
+  category: Category;
+  schema: JsonSchema;
+  path: string;
+}
+
+export const SingleCategory = ({ category, schema, path }: SingleCategoryProps) => {
+  // TODO: add selected style
+  if (category.elements === undefined) {
+    return (<div id='categorization.detail'/>);
```
Comment (eneufeld) [inline src/renderers/additional/categorization-renderer.tsx]: do we need two cases? isn't the second case handling the undefined case?

File: src/renderers/additional/categorization-renderer.tsx [hunk 4]
```diff
@@ -1,12 +1,89 @@
...
 import { Categorization, Category } from '../../models/uischema';
 import { mapStateToLayoutProps, registerStartupRenderer } from '../renderer.util';
 import DispatchRenderer from '../dispatch-renderer';
 import { Component, connect } from '../../common/binding';
+import {JsonSchema} from "../../models/jsonSchema";
+
+const getCategoryClassName = (category: Category, selectedCategory: Category): string =>
+  selectedCategory === category ? 'selected' : '';
+
+export interface CategorizationProps {
```
Comment (eneufeld) [inline src/renderers/additional/categorization-renderer.tsx]: why do we need to export all those props and inner components?

File: src/renderers/controls/boolean.control.tsx [hunk 5]
```diff
@@ -30,7 +30,7 @@ export class BooleanControl extends Control<ControlProps, ControlState> {
           {label}
         </label>
         <input type='checkbox'
-               checked={this.state.value}
+               checked={this.state.value || ''}
```
Comment (eneufeld) [inline src/renderers/controls/boolean.control.tsx]: does checked accept a string? should it be `false` ?

File: src/renderers/controls/date.control.tsx [hunk 6]
```diff
@@ -24,14 +24,15 @@ export class DateControl extends Control<ControlProps, ControlState> {
...
+    const now = new Date().toISOString().substr(0, 10);
 
     return (
       <div className={classNames.wrapper}>
         <label htmlFor={id} className={classNames.label} data-error={errors}>
           {label}
         </label>
         <input type='date'
-               value={this.state.value}
+               value={this.state.value || ''}
```
Comment (eneufeld) [inline src/renderers/controls/date.control.tsx]: this should be `now` not an empty string, doesn't it?

File: src/renderers/controls/enum.control.tsx [hunk 7]
```diff
@@ -42,27 +52,26 @@ export class EnumControl extends Control<ControlProps, ControlState> {
           className={classNames.input}
           hidden={!visible}
           disabled={!enabled}
-          value={this.state.value}
+          value={this.state.value || ''}
```
Comment (eneufeld) [inline src/renderers/controls/enum.control.tsx]: doesn't the value of a `select` control correspond to the key? so shouldn't the alternative be `'empty'` rather than an empty string?

File: src/renderers/controls/integer.control.tsx [hunk 8]
```diff
@@ -32,7 +32,7 @@ export class IntegerControl extends Control<ControlProps, ControlState> {
         </label>
         <input type='number'
                step='1'
-               value={this.state.value}
+               value={this.state.value || ''}
```
Comment (eneufeld) [inline src/renderers/controls/integer.control.tsx]: does an input of type number handle an empty string correctly?

File: test/renderers/textarea.control.test.tsx [hunk 9]
```diff
@@ -274,7 +274,7 @@ test('update with undefined value', t => {
   const textArea = findRenderedDOMElementWithTag(tree, 'textarea') as HTMLTextAreaElement;
   store.dispatch(update('name', () => undefined));
   // keep value
```
Comment (eneufeld) [inline test/renderers/textarea.control.test.tsx]: this comment is wrong now, as we don't keep the value

File: src/json-forms.tsx (hunk 1 above)
Comment (edgarmueller) [reply src/json-forms.tsx]: Yes, kinda.

File: src/renderers/additional/categorization-renderer.tsx (hunk 4 above)
Comment (edgarmueller) [reply src/renderers/additional/categorization-renderer.tsx]: As discussed, we'll keep these in case anyone would create custom renderers for categories.
