### PR TITLE
Fix various errors encountered in examples

### LINKED ISSUE #887: translateProps should check for undefined label

### PR DESCRIPTION
**Pull request by edgarmueller**
Fixes #887 and #888

### CODE REVIEW

File: packages/material/src/complex/MaterialTableControl.tsx [hunk 1]
```diff
@@ -35,7 +35,27 @@ const EmptyTable = () => (
 const TableHeaderCell = ({cellProperty}) =>
   <TableCell >{cellProperty}</TableCell>;
 
-const TableContentCell = ({rowPath, cellProperty, cellPath, errors, resolvedSchema}) => {
+const TableWithContent = tableProps => {
```
Comment (eneufeld) [inline packages/material/src/complex/MaterialTableControl.tsx]: Is this a duplicate of line 86?

Comment (edgarmueller) [reply packages/material/src/complex/MaterialTableControl.tsx]: I think I already updated the PR while you were reviewing it, I don't see the change you are referring to here.
