### PR TITLE
reset data in anyOfRenderer, if data types dont match

### LINKED ISSUE #2173: invalid output from allOf/anyOf combinator
### Describe the bug

Here is my code
```

import { JsonForms } from "@jsonforms/react";
import { useState } from "react";
import {
  materialRenderers,
  materialCells,
} from "@jsonforms/material-renderers";

const Example = () => {
  const [data] = useState({});
  const schema = {
    anyOf: [
      {
        type: "object",
        properties: {
          firstName: {
            type: "object",
            properties: {
              A: {
                type: "number",
                maxLength: 1,
              },
            },
          },
        },
      },
      {
        type: "string",
      },
    ],
  };
  return (
    <JsonForms
      schema={schema}
      uischema={undefined}
      data={data}
      onChange={(d: any) => {
        console.log("getData ", d);
      }}
      renderers={materialRenderers}
      cells={materialCells}
    />
  );
};
```

I got this output: 

image

I cant paste by code because it is a String object. When I copy this object it turns to: 
`{
    "data": "1",
    "errors": []
}`.
Obviously it is not a valid json object.

### Expected behavior

I expected output: 
`
{
    "data": {
        "firstName": {
            "A": 1
        }
    },
    "errors": []
}
` 

### Steps to reproduce the issue

1. Start this example and render:
image
2. select anyof-1 tab & input any string
image
3. select anyof-0 tab & input any string
image
4.  see error on console

### Screenshots

_No response_

### In which browser are you experiencing the issue?

Google Chrome  116.0.5845.96

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

React

### RendererSet

Material

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LukasBoll**
closes #2173

### CODE REVIEW

File: packages/material-renderers/src/complex/ConfirmDialog.tsx [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+      </DialogContent>
+      <DialogActions>
+        <Button onClick={cancel} color='primary'>
+          No
+        </Button>
+        <Button
+          onClick={confirm}
+          color='primary'
+          autoFocus
+          id={`oneOf-${id}-confirm-yes`}
```
Comment (lucas-koehler) [inline packages/material-renderers/src/complex/ConfirmDialog.tsx:49]: The `oneOf` part of the id is not universal and incorrect when used in the any of renderer. Instead, you could hand in an id prefix property that contains the oneOf/anyOf string together with the id prop.

File: packages/material-renderers/src/complex/ConfirmDialog.tsx [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  DialogContentText,
+  DialogTitle,
+} from '@mui/material';
+
+export interface ConfirmDialogProps {
+  open: boolean;
+  handleClose: () => void;
+  confirm: () => void;
+  cancel: () => void;
+  id: any;
```
Comment (lucas-koehler) [inline packages/material-renderers/src/complex/ConfirmDialog.tsx:17]: I would expect this to be of type `string`. Is there a reason for using `any`?

File: packages/material-renderers/src/complex/ConfirmDialog.tsx [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+}
+
+export const ConfirmDialog = ({
```
Comment (lucas-koehler) [inline packages/material-renderers/src/complex/ConfirmDialog.tsx:20]: Could we name this in a way that immediately makes clear what kind of confirmation this dialog is for? E.g. `TabSwitchConfirmDialog`.

File: packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx [hunk 4]
```diff
@@ -46,12 +50,41 @@ export const MaterialAnyOfRenderer = ({
...
+  const [newSelectedIndex, setNewSelectedIndex] = useState(0);
+
+  const handleClose = useCallback(() => setOpen(false), [setOpen]);
+
+  const handleTabChange = useCallback(
+    (_event: any, newIndex: number) => {
+      if (
+        isEmpty(data) ||
+        typeof data ===
+          typeof createDefaultValue(anyOfRenderInfos[newIndex].schema)
```
Comment (lucas-koehler) [inline packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx:67]: What is the purpose of this? Is this to avoid unnecessary confirmations in case the data is "the same"?
If yes, I see a risk of skipping the  confirmation if two anyOfs have the same data type. This could easily happen if they are both objects.
You can test this in the deployed example at https://deploy-preview-2175--jsonforms-examples.netlify.app/react-material/#anyOf
When you change some data and then switch the tab, no confirm dialog is opened.

File: packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx [hunk 5]
```diff
@@ -46,12 +50,41 @@ export const MaterialAnyOfRenderer = ({
...
   uischemas,
-}: StatePropsOfCombinator) => {
+  id,
+  data,
+}: CombinatorRendererProps) => {
   const [selectedAnyOf, setSelectedAnyOf] = useState(indexOfFittingSchema || 0);
-  const handleChange = useCallback(
-    (_ev: any, value: number) => setSelectedAnyOf(value),
-    [setSelectedAnyOf]
+  const [open, setOpen] = useState(false);
```
Comment (lucas-koehler) [inline packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx:57]: Minor: This could be renamed to `confirmDialogOpen` or someting similar to immediately make clear what this is about :)

**Review by lucas-koehler — CHANGES_REQUESTED** [review]
Hi @LukasBoll 
Thanks for the pull request :heart: 
I have some comments inline. Pease have a look.

File: packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx (hunk 4 above)
Comment (LukasBoll) [reply packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx:67]: The purpose was to fix #2173, where unfitting data types would lead to a crash. For example, if you switch between an object and an array. I would argue that the current behaviour is correct. AnyOf means that several of the subschemas can be fulfilled. Resetting the data every time would represent the oneOf option.

**Comment by LukasBoll** [comment]
Thank you very much for the review and your comments! I adressed all of your comments!

File: packages/material-renderers/src/complex/TabSwitchConfirmDialog.tsx [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+      </DialogContent>
+      <DialogActions>
+        <Button onClick={cancel} color='primary'>
+          No
+        </Button>
+        <Button
+          onClick={confirm}
+          color='primary'
+          autoFocus
+          id={id + -'confirm-yes'}
```
Comment (lucas-koehler) [inline packages/material-renderers/src/complex/TabSwitchConfirmDialog.tsx:49]: The `+ -'confirm-yes'` looks suspicious to me. Testing something like this in the browser console `-'avc'` is converted to `NaN`. Instead you can simply to it together via a template string.
```suggestion
          id={`${id}-confirm-yes`}
```

File: packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx (hunk 4 above)
Comment (lucas-koehler) [reply packages/material-renderers/src/complex/MaterialAnyOfRenderer.tsx:70]: That makes sense. Thanks for the explanation :)

**Review by lucas-koehler — CHANGES_REQUESTED** [review]
Hi @LukasBoll , thanks for the updates. I found one small bug inline and added a suggestion to fix it.

**Review by lucas-koehler — APPROVED** [review]
@LukasBoll I merged the minor suggested fix. Thanks again for the contribution :)
