### PR TITLE
generate a control for enums in generated uischema

### LINKED ISSUE #2177: Enum without "type" can't be rendered
### Describe the bug

Enum definition without "type", like:

```json
{
  "enum": ["A", "B"]
}
```

, is valid JSON Schema, but can't be rendered.

### Expected behavior

Rendered as normal enum.

### Steps to reproduce the issue

The following schema does not render any fields:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "foo": {
      "enum": ["A"]
    }
  }
}
```

image

And the following schema causes runtime error, `options is undefined` at [this line](https://github.com/eclipsesource/jsonforms/blob/1e44159b4e9e7aaf4f5324b6f67636e5e35bd777/packages/material-renderers/src/mui-controls/MuiAutocomplete.tsx#L85):

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "foo": {
      "type": "string",
      "anyOf": [
        {
          "enum": ["A", "B"]
        },
        {
          "enum": ["C", "D"]
        }
      ]
    }
  }
}
```

image

### Screenshots

_No response_

### In which browser are you experiencing the issue?

Firefox 117.0 (64-bit Windows)

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

React

### RendererSet

Material

### Additional context

I don't give any UI Schema(using default behavior).

### PR DESCRIPTION
**Pull request by LukasBoll**
closes #2177

### CODE REVIEW

File: packages/core/src/util/util.ts [hunk 1]
```diff
@@ -77,7 +77,17 @@ export const deriveTypes = (jsonSchema: JsonSchema): string[] => {
...
     return ['array'];
   }
-
+  if (!isEmpty(jsonSchema.enum)) {
+    const types: Set<string> = new Set();
+    jsonSchema.enum.forEach((enumElement) => {
+      if (typeof enumElement === 'string') {
+        types.add('string');
+      } else {
+        deriveTypes(enumElement).forEach((type) => types.add(type));
```
Comment (sdirix) [inline packages/core/src/util/util.ts:86]: We need to check whether the array has a single item. If yes, then we should return that directly instead of an array

**Review by lucas-koehler — APPROVED** [review]
LGTM thanks :)

File: packages/core/src/util/util.ts (hunk 1 above)
Comment (lucas-koehler) [reply packages/core/src/util/util.ts:86]: If we want to do that we should adapt the type definition of the deriveTypes function as it only declares string[] as a return type. Furthermore, we also return single value arrays further above. So IMO we can leave it like that.

Comment (lucas-koehler) [reply packages/core/src/util/util.ts:86]: @sdirix Or am I missing something?

Comment (sdirix) [reply packages/core/src/util/util.ts:86]: @lucas-koehler you are right. I was too fast when reviewing and got the use case of this function confused. The code is fine.
