### PR TITLE
Additional fixes

### LINKED ISSUE #518: Add category example

### LINKED ISSUE #519: Add master-detail example

### LINKED ISSUE #520: Add remote JSON ref example

### PR DESCRIPTION
**Pull request by eneufeld**
Fixes #518 
Fixes #519 
Fixes #520

### CODE REVIEW

File: src/generators/ui-schema-gen.ts [hunk 1]
```diff
@@ -15,13 +15,16 @@ const createLayout = (layoutType: string): Layout => ({
 /**
  * Derives the type of the jsonSchema element
  */
-const deriveType = (jsonSchema: any): string => {
-    if (jsonSchema.type) {
+const deriveType = (jsonSchema: JsonSchema): string => {
+    if (jsonSchema.type && typeof jsonSchema.type === 'string') {
```
Comment (edgarmueller) [inline src/generators/ui-schema-gen.ts]: Are we only checking for `string` here because of the fall-through cases in `generateUISchema`? If yes, I'd prefer explicit checks for the other primitives as well.

File: src/renderers/additional/tree-renderer.ts [hunk 2]
```diff
@@ -66,28 +66,55 @@ class TreeRenderer extends Renderer implements DataChangeListener {
     const controlElement = <ControlElement> this.uischema;
     const arrayData = this.dataService.getValue(controlElement);
     if (arrayData !== undefined && arrayData.length !== 0) {
-      this.renderDetail(arrayData[0], this.master.lastChild.firstChild);
+      let firstChild = arrayData;
+      if (Array.isArray(firstChild)) {
+        firstChild = firstChild[0];
```
Comment (edgarmueller) [inline src/renderers/additional/tree-renderer.ts]: Taste of preference, but I'd remove the `firstChild` var and inline the `renderDetail`. Could you add a comment to `this.master.lastChild.firstChild.firstChild`, which looks kinda weird.

File: test/schema-gen.test.ts [hunk 3]
```diff
@@ -3,6 +3,97 @@ import test from 'ava';
...
+    'additionalProperties': true,
+    'required': [
+      'emptyArray', 'booleanArray', 'numberArray', 'integerArray', 'stringArray', 'nullArray'
+    ]
+  });
+});
+test.skip('default schema generation tuple array types', t => {
+  const instance = {tupleArray: [3.14, 'PI']};
+  const schema = generateJsonSchema(instance);
+  // FIXME: This assumption is the correct one, but we crteate a oneOf in this case
```
Comment (edgarmueller) [inline test/schema-gen.test.ts]: I guess this should probably be tracked as an issue, if it's not already the case.

File: example/templates/categorization.ts [hunk 4]
```diff
@@ -0,0 +1,181 @@
...
+};
+const data = {
+  name: 'John Doe',
+  vegetarian: false,
+  birthDate: '1985-06-02',
+  nationality: 'DE'
+};
+registerExamples([
+  {name: 'categorization', label: 'Categorization', data: data, schema: schema, uiSchema: uischema}
+  // ,
```
Comment (eneufeld) [inline example/templates/categorization.ts]: created follow up

File: example/templates/masterdetail.ts [hunk 5]
```diff
@@ -0,0 +1,256 @@
...
+      'properties': {
+        'name': {
+          'type': 'string',
+          'minLength': 3
+        },
+        'folders': {
+          'type': 'array',
+          'items':
+          {
+            // TODO make recursive
```
Comment (eneufeld) [inline example/templates/masterdetail.ts]: created follow up

File: example/templates/masterdetail.ts [hunk 6]
```diff
@@ -0,0 +1,256 @@
...
```
Comment (eneufeld) [inline example/templates/masterdetail.ts]: created follow up

File: example/templates/masterdetail.ts [hunk 7]
```diff
@@ -0,0 +1,256 @@
...
+      },
+      'required': ['name']
+    }
+  },
+  'type': 'object',
+  'id': '#drive_object',
+  'properties': {
+    'name': {
+      'type': 'string',
+      'minLength': 3
```
Comment (eneufeld) [inline example/templates/masterdetail.ts]: this is fixed in another pull request

File: src/generators/ui-schema-gen.ts (hunk 1 above)
Comment (eneufeld) [inline src/generators/ui-schema-gen.ts]: this is a typeof check, so we check for the type property being a string and not a string array

File: src/renderers/additional/tree-renderer.ts (hunk 2 above)
Comment (eneufeld) [inline src/renderers/additional/tree-renderer.ts]: lets check this in the later pull requests and create an issue for style guidelines

File: test/schema-gen.test.ts (hunk 3 above)
Comment (eneufeld) [inline test/schema-gen.test.ts]: thats a test, in a future version this is marked as failing

File: src/generators/ui-schema-gen.ts (hunk 1 above)
Comment (edgarmueller) [inline src/generators/ui-schema-gen.ts]: Ah, true, I've missed the `typeof`.
