### PR TITLE
Return comment if no fitting renderer was found

### LINKED ISSUE #267: Complete Rendering fails when no renderer is found for one UI schema element
The rendering should be more graceful and log the error (e.g. into the DOM as comment) but continue rendering

### PR DESCRIPTION
**Pull request by eneufeld**
Fixes #267

### CODE REVIEW

**Comment by eneufeld** [comment]
@edgarmueller please review

File: src/components/renderers/renderer-service.ts [hunk 1]
```diff
@@ -29,10 +29,14 @@ class RendererServiceImpl implements RendererService {
         this.renderer.push({directiveName: directiveName, tester: tester});
     }
     getBestComponent(element: IUISchemaElement, dataSchema: any, dataObject: any): string {
-        let bestRenderer = _.maxBy(this.renderer, renderer =>
-            renderer.tester(element, dataSchema, dataObject, this.pathResolver)
-        );
-
+        let bestRenderer = _.maxBy(this.renderer, renderer => {
+            let result = renderer.tester(element, dataSchema, dataObject, this.pathResolver);
+            return result === NOT_FITTING ? null : result;
```
Comment (edgarmueller) [inline src/components/renderers/renderer-service.ts]: Why do we need to return `null`? Why don't we compare `bestRenderer` with `NOT_FITTING`?

**Comment by edgarmueller** [comment]
Looks good, thanks!
