### PR TITLE
Fixed the no data state of the array renderer

### LINKED ISSUE #1040: Empty array renderer looks weird
When rendering an empty array, it looks like follows:

selection_062

Two minor issues are:
1. The checkbox should not be checked
2. The 'No data' label is too small and does not span the entire width of the control

### PR DESCRIPTION
**Pull request by eneufeld**
Fixes #1040

### CODE REVIEW

File: packages/material/src/complex/MaterialTableControl.tsx [hunk 1]
```diff
@@ -73,17 +73,22 @@ const generateHeaderCellForPrimitives = toolbarProps => {
     </TableCell>
   );
 };
+const getValidColumnProps = (scopedSchema: JsonSchema) =>
```
Comment (edgarmueller) [inline packages/material/src/complex/MaterialTableControl.tsx]: This seems to crash when first clicking 'select all', followed by a delete. We should also add a test case covering this scenario.
