### PR TITLE
Transform CategorizationRenderer from class to functional

### LINKED ISSUE #2097: React Vanilla Categorization Renderer should handle updated schemas
### Describe the bug

The React Vanilla Categorization renderer maintains local state about the currently selected category. This state is not properly updated when the UI Schema changes and therefore may return a previous category which no longer fits the JSON Schema.

### Expected behavior

Whenever a prop of the React Vanilla Categorization renderer changes it should update accordingly.

### Steps to reproduce the issue

1. Render a categorization with React Vanilla
2. Select a category
3. Replace schema and uischema with a new Categorization but whose content is completely different
4. Still the old category of the previous uischema is used, leading for example to "No applicable cell" errors

The problematic code seems to be [here](https://github.com/eclipsesource/jsonforms/blob/386174994eabc41758450b8d551e1c859498a468/packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx#L93-L97).

### Screenshots

_No response_

### In which browser are you experiencing the issue?

n/a

### Which Version of JSON Forms are you using?

3.0.0

### Framework

React

### RendererSet

Vanilla

### Additional context

Reported in this [discussion](https://jsonforms.discourse.group/t/how-to-re-inizalize-a-complex-json-form/1338)

### PR DESCRIPTION
**Pull request by TheZoker**
This should fix #2097

### CODE REVIEW

**Review by sdirix — CHANGES_REQUESTED** [review]
Please add a test case.

I don't think the error is fixed. The current category is still saved in state and is not updated on ui schema changes.

File: packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx [hunk 1]
```diff
@@ -22,88 +22,105 @@
...
+  useJsonForms,
   withJsonFormsLayoutProps,
   withTranslateProps,
 } from '@jsonforms/react';
 import { CategorizationList } from './CategorizationList';
 import { SingleCategory } from './SingleCategory';
-import { isCategorization } from './tester';
 import { withVanillaControlProps } from '../../util';
-import type { VanillaRendererProps } from '../../index';
+import type { AjvProps, VanillaRendererProps } from '../../index';
```
Comment (sdirix) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx:37]: We should not import from a parent index

Comment (TheZoker) [reply packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx:37]: I think the issue is, that the types are defined in that index file.
e.g.: https://github.com/eclipsesource/jsonforms/blob/master/packages/vanilla-renderers/src/index.ts#L86-L103

Comment (sdirix) [reply packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx:37]: That's not good. I would prefer if the `index` files only export and do nothing on their own. Can you refactor this and move the types and renderers each to an own file?

Comment (TheZoker) [reply packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx]: Done

File: packages/vanilla-renderers/src/complex/categorization/CategorizationList.tsx [hunk 2]
```diff
@@ -37,7 +36,7 @@ const getCategoryClassName = (
 ): string => (selectedCategory === category ? 'selected' : '');
 
 export interface CategorizationProps {
-  categorization: Categorization;
+  filteredCategories: [Category];
```
Comment (lucas-koehler) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationList.tsx:39]: I think this type is incorrect: `[Category]` is an array with exactly one `Category` element. `Category[]` is a normal array of `Category` elements.

Furthermore, I think handing in only the filtered categories is not enough. Child categorizations are lost with this approach. I think the type should probably be `(Category | Categorization)[]` to allow both. In fact it effectively gets an array of this type at the moment because `Categorization`s are not filtered out in `CategorizationRenderer` ;)

File: packages/vanilla-renderers/src/complex/categorization/CategorizationList.tsx [hunk 3]
```diff
@@ -57,22 +56,20 @@ export const CategorizationList = ({
...
-      {categorization.elements.map((category, idx) => {
+      {filteredCategories.map((category, idx) => {
         if (isCategorization(category)) {
           return (
             <li key={categoryLabels[idx]} className={groupClassName}>
               <span>{categoryLabels[idx]}</span>
               <CategorizationList
-                categorization={category}
                 selectedCategory={selectedCategory}
+                filteredCategories={filteredCategories}
```
Comment (lucas-koehler) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationList.tsx:72]: This is causing the endless loop and, thus, the Node out of memory error in the tests.  Basically you hand in the same categories as were handed in the current `CategorizationList`. This results in an endless loop. Instead, you need the elements contained in `category`

File: packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx [hunk 4]
```diff
@@ -22,88 +22,105 @@
...
+  t,
+  visible,
+  getStyleAsClassName,
+  onChange,
+}: LayoutProps &
+  VanillaRendererProps &
+  TranslateProps &
+  CategorizationProps &
+  AjvProps) => {
+  const ajv = useJsonForms().core.ajv;
```
Comment (lucas-koehler) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx:63]: You should not need this because `ajv` is already given as part of the props as indicated by the `AjvProps` type. To actually get this handed in, make sure to wrap the export at the end of this file with `withAjvProps`

File: packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx [hunk 5]
```diff
@@ -22,88 +22,105 @@
...
+  const categorization = uischema as Categorization;
+  const filteredCategories = useMemo(
+    () =>
+      categorization.elements.filter((category: Category) =>
+        isVisible(category, data, undefined, ajv)
+      ),
+    [categorization, data, ajv]
+  ) as [Category];
```
Comment (lucas-koehler) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx:71]: This is not what the useMemo returns because `[Category]` is an array (or tuple) with exactly one `Category` element.

File: packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx [hunk 6]
```diff
@@ -22,88 +22,105 @@
...
+}: LayoutProps &
+  VanillaRendererProps &
+  TranslateProps &
+  CategorizationProps &
+  AjvProps) => {
+  const ajv = useJsonForms().core.ajv;
+  const categorization = uischema as Categorization;
+  const filteredCategories = useMemo(
+    () =>
+      categorization.elements.filter((category: Category) =>
```
Comment (lucas-koehler) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx:67]: The type used in the method argument is not correct because `categorization.elements` is of type `(Category | Categorization)[]`. IF you want to get rid of the sub-categorizations, they need to be filtered out here. However, I think the `CategorizationList` rendered below also needs to know of child `Catagorization` elements. Otherwise nested categorizations can no longer be rendered. Or am I missing something?

**Review by lucas-koehler — CHANGES_REQUESTED** [review]
Hi @TheZoker , thanks for the contribution.
I left some comments inline. Please have a look :) The two main issues atm seem to be:

- In `CategorizationList`, and endless loop is created by handing down the same `filteredCategories`. This causes the out of memory error during tests. More details are in the comment inline
- The new `filteredCategories` prop is of the wrong type and does not consider `Categorization` elements despite them effectively being handed down. Handing them down seems to be correct because otherwise we could no longer handle nested `Categorization`s. The type and potentially the prop name should be fixed accordingly.

File: packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx [hunk 7]
```diff
@@ -22,89 +22,105 @@
...
+  getStyleAsClassName,
+  onChange,
+  ajv,
+}: LayoutProps &
+  VanillaRendererProps &
+  TranslateProps &
+  CategorizationProps &
+  AjvProps) => {
+  const categorization = uischema as Categorization;
+  const elements = useMemo(
```
Comment (lucas-koehler) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationRenderer.tsx:63]: This memo is superfluous because `categorization.elements` does not change. Thus, the `useMemo` should be removed

File: packages/vanilla-renderers/src/complex/categorization/CategorizationList.tsx [hunk 8]
```diff
@@ -24,55 +24,65 @@
...
+  data,
   depth,
   onSelect,
   subcategoriesClassName,
   groupClassName,
   t,
-}: CategorizationProps) => {
+  ajv,
+}: CategorizationProps & AjvProps) => {
+  const filteredElements = elements.filter(
```
Comment (lucas-koehler) [inline packages/vanilla-renderers/src/complex/categorization/CategorizationList.tsx:63]: This should be memoed via a `useMemo`. Otherwise, the memo for the `categoryLabels` is useless because `filteredElements` is recalculated on each render and, thus, breaks the memo of `categoryLabels`.

**Review by lucas-koehler — CHANGES_REQUESTED** [review]
Thanks for the updates. Looks better now :) I have two remarks inline.
Furthermore, the vanilla example app and some tests for the input control and the categorization renderer are failing.
I have a suspicion regarding the example app and input control: `packages/vanilla-renderers/src/util/renderer.ts` being in the `util` folder creates a circular dependency. Thus, `renderer.ts` should be moved up one folder to be directly contained in the `src` folder.
Please also have a look at the categorization renderer tests.

**Comment by lucas-koehler** [comment]
@TheZoker Thanks for the updates :)
The test case Categorization renderer › reset selected category on schema change is still failing. Please have a look.

File: packages/vanilla-renderers/src/renderer.ts
Comment (sdirix) [inline packages/vanilla-renderers/src/renderer.ts:1]: This file should be called `renderers` as we typically use plurals.

File: packages/vanilla-renderers/src/renderer.ts [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+
+import {
+  GroupLayout,
+  groupTester,
+  HorizontalLayout,
+  horizontalLayoutTester,
+  VerticalLayout,
+  verticalLayoutTester,
+} from './layouts';
+import DateTimeCell from './cells/DateTimeCell';
```
Comment (sdirix) [inline packages/vanilla-renderers/src/renderer.ts:78]: Can you align this import with the others?

**Review by sdirix — COMMENTED** [review]
Looks good! Can you squash this into 1-2 nicely formatted commits?

**Review by sdirix — APPROVED** [review]
